name: Build and Push Docker Image to ECR

on:
    workflow_dispatch:
      inputs:
        confirmation:
          description: 'Type "yes" to confirm deployment'
          required: true
          default: 'no'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          aws-region: eu-west-2

      - name: Build, tag as latest, and push Docker image to ECR
        id: build-image
        env:
          ECR_REGISTRY: 009160072276.dkr.ecr.eu-west-2.amazonaws.com/qais/threat-project
        run: |
          docker build -t $ECR_REGISTRY:latest .
          docker push $ECR_REGISTRY:latest
          # echo "image=$ECR_REGISTRY:latest" >> $GITHUB_OUTPUT
