name: 'CI-CD Terraform build'

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Type "yes" to confirm deployment'
        required: true
        default: 'no'

permissions:
  contents: read
  pull-requests: write

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'us-east-1'
  DISCORD_WEBHOOK_URL: ${{secrets.DISCORD_WEBHOOK_URL}}

jobs:

  security_scan_app:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: Pull Docker image from ECR
        run: |
          IMAGE_URI=767398132018.dkr.ecr.us-east-1.amazonaws.com/mohammedsayed/threat-composer:latest
          docker pull $IMAGE_URI

      - name: Scan Docker image for vulnerabilities (App)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 767398132018.dkr.ecr.us-east-1.amazonaws.com/mohammedsayed/threat-composer:latest
          exit-code: 1 
          severity: CRITICAL 
          
      - name: Discord noti on Successful Security Scan
        if: success()
        run: |
              BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}")
              TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
              COMMITTER=${GITHUB_ACTOR}
              curl -H "Content-Type: application/json" \
              -d "{\"content\": \"✅ Security scan successful: in repo ${{ github.event.repository.name }}, ${BRANCH_NAME} at ${TIMESTAMP}. Committer: ${COMMITTER}\"}" \
              ${{ secrets.DISCORD_WEBHOOK_URL }}

  terraform_static_analysis:
    name: 'Terraform Static Analysis'
    needs: security_scan_app
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform Format
        run: terraform fmt --recursive
        working-directory: terraform

      - name: Terraform Format check
        working-directory: terraform  
        run: |
          terraform fmt -check
          if [ $? -ne 0 ]; then
            exit 1
          fi

      - name: Terraform Initialise
        working-directory: terraform  
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform  
        run: terraform validate

      - name: Install tflint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          tflint --version

      - name: Terraform Lint
        working-directory: terraform  
        run: tflint

  terraform_plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    needs: terraform_static_analysis
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform Plan
        working-directory: terraform  
        id: tf-plan
        run: |
          terraform init
          terraform plan -out=plan-test  
          terraform show -no-color plan-test > tf-plan.txt
      
      - name: Upload Terraform Plan Artifact 
        uses: actions/upload-artifact@v3
        with:
          name: tf-plan
          path: terraform/tf-plan 

  terraform_apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    needs: [terraform_plan]
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.confirmation == 'yes'
    steps:
      - uses: actions/checkout@v2

      - name: Terraform Apply
        working-directory: terraform  
        run: |
          terraform init
          terraform apply --auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'

      - name: Send Discord Notification on Success build
        if: success()
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}")
          TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          COMMITTER=${GITHUB_ACTOR}
          curl -H "Content-Type: application/json" \
          -d "{\"content\": \"✅ Application built succesfully: in repo ${{ github.event.repository.name }}, ${BRANCH_NAME} at ${TIMESTAMP}. Committer: ${COMMITTER}\"}" \
           ${{ secrets.DISCORD_WEBHOOK_URL }}
